### ISSUE TITLE
No mediator for main class

### ISSUE THREAD

**Issue by matej-snivam** [kavolorn/GizmoDuck#1]
Hello,

My main starling class is not being mediated. I have to instantiate starling before I initialize robotlegs.

Is your extension searching the stage for already added display objects like native stage crawler?

**Comment by kavolorn** [comment]
Hello! Take a look at example code on my blog: http://kavolorn.ru/en/post/read/postId/128. I have ApplicationView which is the first container in application and it is mediated correctly.
